### ISSUE TITLE
Error build under gcc 8.3.1

### ISSUE THREAD

**Issue by asafov** [eteran/p0f-ng#1]
Hello, dear Evan.

There is an error make under Centos 7, gcc 8.3.1

> [root@apps p0f-ng]# scl enable devtoolset-8 bash
> [root@apps p0f-ng]# cmake3 .
> -- The C compiler identification is GNU 8.3.1
> -- The CXX compiler identification is GNU 8.3.1
> -- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc
> -- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++
> -- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PCAP: /usr/lib64/libpcap.so  
> -- Performing Test PCAP_LINKS_SOLO
> -- Performing Test PCAP_LINKS_SOLO - Success
> -- Boost 1.61 found.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/p0f-ng
> [root@apps p0f-ng]# make
> Scanning dependencies of target p0f-engine
> [ 10%] Building CXX object lib/CMakeFiles/p0f-engine.dir/fp_http.cpp.o
> In file included from /root/p0f-ng/lib/fp_http.cpp:23:
> /root/p0f-ng/lib/hash.h: In function ‘constexpr uint32_t hash32(const void*, uint32_t)’:
> /root/p0f-ng/lib/hash.h:33:13: error: call to non-‘constexpr’ function ‘uint32_t RD32p(const void*)’
>    a += RD32p(k);
>         ~~~~~^~~
> make[2]: *** [lib/CMakeFiles/p0f-engine.dir/build.make:63: lib/CMakeFiles/p0f-engine.dir/fp_http.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:91: lib/CMakeFiles/p0f-engine.dir/all] Ошибка 2
> make: *** [Makefile:84: all] Error 2

Need your help with this

**Comment by eteran** [comment]
Looks like something isn't supporting C++14 for some reason, I'll double check this and fix it up as needed.

**Comment by asafov** [comment]
At Debian 10 is same problem.

**Comment by eteran** [comment]
OK, seems that gcc-8.x has broken c++14 support. I'll work around it :+1:

**Comment by eteran** [comment]
It should be fixed in the latest master. Thanks for the report!
