### ISSUE TITLE
Save mtu value to API

### ISSUE THREAD

**Issue by asafov** [eteran/p0f-ng#2]
Idea based on this patch:

https://github.com/ValdikSS/p0f-mtu/blob/14d109575391c92a4f5a76041e7d7373053b1eef/api.c#L91

https://github.com/ValdikSS/p0f-mtu/blob/14d109575391c92a4f5a76041e7d7373053b1eef/fp_mtu.c#L89

https://github.com/ValdikSS/p0f-mtu/blob/14d109575391c92a4f5a76041e7d7373053b1eef/api.h#L67

https://github.com/ValdikSS/p0f-mtu/blob/14d109575391c92a4f5a76041e7d7373053b1eef/process.h#L108

**Comment by eteran** [comment]
Seems simple enough, should be doable :+1:
